# Generated by Django 5.0.6 on 2024-05-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=30)),
                ('ingredientes_receita', models.CharField(max_length=500)),
                ('descricao_receita', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Alunos',
        ),
    ]
